### PR TITLE
Adding fix to subscribe() call with raw node pointer and subscriber options

### PR DESCRIPTION
**Pull request by SteveMacenski**
Per https://github.com/ros2/message_filters/issues/75

### CODE REVIEW

**Review by gbiggs — APPROVED** [review]

**Comment by SteveMacenski** [comment]
I'm 3 hours into the ~4 hours needed to build all of ROS 2 / underlay / nav2 from source to test this with the forked version of `message_filters` to make sure this is the only / correct issue. Hopefully I should be able to confirm in the next couple of hours, but either way this is an error.

**Comment by SteveMacenski** [comment]
Well I've given up on this, there's a bunch of python conflicts with my installs  (launch won't launch, cli won't cli) and I'm not going to fix all of those issues for just testing this. https://github.com/ros2/rclcpp/issues/1954 identifies that there is also an issue in or below `rclcpp` but this is also a component of it.

**Comment by SteveMacenski** [comment]
@gbiggs can we get this into a new Rolling / Humble release? That would help fix Nav2 in the next sync

**Comment by gbiggs** [comment]
Backport to Humble and releases for Humble and Rolling are done! The fix should be in the next sync of each. Ping me if it doesn't appear.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-06-16/26093/1

**Pull request merged**
