### PR TITLE
fixed using wrong type of stamp

### PR DESCRIPTION
**Pull request by ahuizxc**
In the current code, when stamp = msg.header.stamp, it will raise errors because msg.header.stamp is builtin_interfaces.msg.Time, and it doesn't have nanoseconds attribute. So i fixed this problem :)

### CODE REVIEW

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5528/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2188/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4563/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5424/)

**Comment by mjcarroll** [comment]
@ahuizxc It appears that there are some failing tests in the CI. Please update to fix these.

**Comment by ahuizxc** [comment]
> @ahuizxc It appears that there are some failing tests in the CI. Please update to fix these.

I think there are something wrong about test case code, should i modify the test code ?

**Comment by ahuizxc** [comment]
> Yes, that's totally reasonable. We expect all tests to pass (or at least no new tests to break) before merging changes.

Already done! Thanks for your time :)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5554/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2201/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4576/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5437/)

**Comment by mjcarroll** [comment]
That failure was an issue that we saw before, but should be resolved on Windows.  I'm going to trigger it again to make sure it wasn't just a flake.
[Build Status](https://ci.ros2.org/job/ci_windows/)

**Pull request merged**
