### PR TITLE
Add lifecycle node support

### PR DESCRIPTION
**Pull request by allenh1**
This is a revival of #37.

The original changeset made by @jcmonteiro has been rebased on the latest code + adapted where necessary, and the feedback left by @Karsten1987 has been addressed.

Let me know if there's anything else that should go in!

### CODE REVIEW

**Comment by gezp** [comment]
I have a idea to improve it, when we want to use Subscriber for `LifecycleNode`, we should  define 
```c++
message_filters::Subscriber<sensor_msgs::msg::LaserScan,rclcpp_lifecycle::LifecycleNode>  sub_;
// it looks like too long
```
we can adapt `Subscriber`  class to be used with `LifecycleNode` or `Node`  by using  `rclcpp::node_interfaces::NodeBaseInterface::SharedPtr` , [a example in tf2_ros/transform_listener.h](https://github.com/ros2/geometry2/blob/bd125c5af32e2c63c70b7e0ba88e57094714b9b8/tf2_ros/include/tf2_ros/transform_listener.h#L111-L120)  , like this:
```bash
template<class NodeT>
Subscriber(NodeT &&node, ...){
   node_base_interface_ = node->get_node_base_interface();
}
```
then, we can create subscription by using `node_base_interface_`  .

**Comment by SteveMacenski** [comment]
@mjcarroll can you rerun CI? 

@tfoote @Karsten1987 can you re-review and/or approve this PR? I believe it meets all of the requirements Karsten wanted. It's something we're trying to use in Nav2 in order to remove excess `rclcpp::Node`'s from our servers as part of @gezp's summer project with me.

**Comment by mjcarroll** [comment]
@ros-pull-request-builder retest this please

**Review by Karsten1987 — APPROVED** [review]

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Thank you both for the help! Does this need a second maintainer review to be merged? Else, I'd reviewed independently and am satisfied with this solution.

**Comment by SteveMacenski** [comment]
@mjcarroll can we get a sync with rolling?

**Comment by mjcarroll** [comment]
@SteveMacenski https://github.com/ros/rosdistro/pull/30350

**Comment by SteveMacenski** [comment]
Thank you!

**Pull request merged**
