### PR TITLE
Fast-forward merge pytest.ini to Foxy

### PR DESCRIPTION
**Pull request by jacobperron**
This should help resolve one of the outstanding failures in https://github.com/ros2/ci/pull/503

### CODE REVIEW

**Comment by clalancette** [comment]
Change looks OK, but any idea why the PR job failed?

**Comment by jacobperron** [comment]
No idea, but I think it's the same issue affecting all PR jobs.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (using custom job config from ros-infrastructure/ros_buildfarm#828)

**Comment by jacobperron** [comment]
CI for this PR and several other similar backports can be found here: https://github.com/ros2/ci/pull/503#issuecomment-673751744

**Pull request merged**
