### PR TITLE
Mark subscription cb parameter const

### PR DESCRIPTION
**Pull request by roncapat**
See #31.
We can use `const ConstSharedPtr` here.

### CODE REVIEW

**Review by ZhenshengLee — APPROVED** [review]
lg2m

**Comment by clalancette** [comment]
Would it be possible to add a test showing this in use?  That is, add a test that would have failed before this PR, but now succeeds.

**Comment by roncapat** [comment]
As pointed out in https://github.com/ros2/message_filters/issues/31#issuecomment-1749785441, it may not be beneficial in terms of performances.
Nevertheless, the `EventType` contructor takes a `const shared_ptr<>`:
https://github.com/ros2/message_filters/blob/856488d894657a296b249ebbc2feebeafcba8917/include/message_filters/message_event.h#L118C7-L118C7
so why not mark it `const` here, as the use of the lambda parameter gets only read, to remark this fact?

In the meantime, I'm trying to check with @tonynajjar if this also helps enabling Intra-process comms or not, because per this comment https://github.com/ros2/message_filters/issues/31#issuecomment-1749785441 I remembered that the possible signatures of intra-process compatible subscription callbacks were quite few, and in my code I took the habit to use `const MsgType::ConstSharedPtr` but looking into `rclcpp` now there seems to me that just using `MsgType::ConstSharedPtr` would still be fine.

In the latter case, `message_filters` is already IPC-enabled, unless I'm missing other bottlenecks / internal message copies somewhere else.

**Comment by roncapat** [comment]
@clalancette I've changed title. Let me know if my last message rationale is good for you.

**Comment by clalancette** [comment]
> In the latter case, `message_filters` is already IPC-enabled, unless I'm missing other bottlenecks / internal message copies somewhere else.

Yeah, I doubt this change is going to make much difference.  We are already using the `const ConstMessagePtr` signature of `MessageEvent` in any case, so passing it along like this is just a small hint to the compiler.  I don't think it is going to make a measurable performance difference.

That said, I'm not against adding it in.

**Comment by roncapat** [comment]
As you want :) 

Yep, this is definitely to be considered as just a compiler hint (and developer hint, if someone reads the code), no additional feature.

**Comment by clalancette** [comment]
I'll run CI on this, just to check that it is OK.  Assuming that is good, I'll merge it in:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19644/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14152/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20368/)

**Pull request merged**
