### PR TITLE
fix: fallback Time used incorrect clock

### LINKED ISSUE #117: `rclcpp::Time` source difference causing crash using `ApproximateEpsilonTime`
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  can't compare times with different time sources
```

Offending line is:

https://github.com/ros2/message_filters/blob/541d8a5009b14aaae4d9fe52e101273e428bb5d0/include/message_filters/sync_policies/approximate_epsilon_time.h#L142

```
142	   if (current.first > candidate) {
gef➤  p current.first
$1 = {
  _vptr.Time = 0x7ffff7efa928 <vtable for rclcpp::Time+16>,
  rcl_time_ = {
    nanoseconds = 0x7fffffffffffffff,
    clock_type = RCL_ROS_TIME
  }
}
gef➤  p candidate
$2 = {
  _vptr.Time = 0x7ffff7efa928 <vtable for rclcpp::Time+16>,
  rcl_time_ = {
    nanoseconds = 0x0,
    clock_type = RCL_SYSTEM_TIME
  }
}
gef➤  
```

### PR DESCRIPTION
**Pull request by russkel**
fixes #117

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
Looks good to me with green CI.

Let's put this on the queue to merge after the freeze is lifted.

**Comment by CursedRock17** [comment]
Friendly Ping, is the CI ready to be run since technically the freeze is over?

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21237/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15555/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/714/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21959/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to merge with `rolling` ?

**Comment by russkel** [comment]
> Do you mind to merge with `rolling` ?

I was hoping for a back port for jazzy, but it's not a big issue.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21246/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15566/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/727/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21968/)

**Comment by russkel** [comment]
Hi @ahcorde, could this please be back ported to Jazzy? I think it's a pretty relevant fix for LTS.

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Comment by russkel** [comment]
> https://github.com/Mergifyio backport jazzy

Thanks!

**Pull request merged**
